apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: blackvoxel-staging
type: Opaque
stringData:
  # --- Core runtime ---
  RUST_LOG: info
  BIND_ADDR: http://0.0.0.0:8081
  # Allow both localhost and 127.0.0.1 while testing via port-forward/ingress.
  CORS_ALLOWED_ORIGINS: http://127.0.0.1:8081,http://localhost:8081
  # Local port-forward uses http, not https.
  DISCORD_REDIRECT_URI: http://127.0.0.1:8081/auth/callback

  # --- Staging DB (ephemeral Postgres in-cluster) ---
  # Service name from apps/postgres-staging is `postgres-staging` in namespace `blackvoxel-staging`.
  # If your Rust app uses a different env var name, adjust accordingly.
  DATABASE_URL: postgres://blackvoxel:blackvoxel@postgres-staging:5432/blackvoxel?sslmode=disable
  JWT_SECRET: "UnBCvetntmdrPs+eGjYKeBrpw+6W/CvafvIWIxUNvhE="
  DISCORD_CLIENT_ID: "1380572212636942427"
  DISCORD_CLIENT_SECRET: "yqeA79dCSwYtmgIksLfYdbmsmfP3V3w1"

  # --- Redis (staging) ---
  # If you deploy redis in staging with a different service name/port, adjust accordingly.
  # If backend treats REDIS_URL as required and you don't use redis on staging, remove this and
  # update backend to make it optional.
  REDIS_URL: redis://redis:6379

  # --- Public URL ---
  # Set to whatever you use to access staging (port-forward, local ingress hostname, etc.)
  PUBLIC_BASE_URL: http://127.0.0.1:8081/api
