---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: blackvoxel
spec:
  encryptedData:
    .dockerconfigjson: AgAYRly6dfLW2iZFMC6pMBzY4LqdHZLATqLAdyYgU5SkQz+7hrFtn7rCocerN5904IuqDhGkN9O8E8GR9/8GJh1wXCo4MzB+DqQV/iUmMjq7qmGVeytxb7G3xsg00SFP5PHI98Xm55/UtBxYuNJQxJVdCGURXxSWKnuxTInUWBSu67C1EdDn06cAABzbJMV3fiaelIcJf2K+M9qnLvnoMLcOReoVdwcQLdH3mhEPT+ISou68ZuIIZIAmkc6wL6q2kys2nPyEU+j8d44Pbo+c1N7nI0WBtOhQ9eV/s7zO+UIOlxlnaww4ZomJF9szO/2CQ1ArxlzdqNdr5geOoBxKXw4yBrSDh5AyLeAf4glM3135J/qjIx4OVrWa1DKGf0yxBKnwdAM2QOdhuEdZD1kscxOflYGf4skqyLdQ+oh8L+WJAOVK5OMQPynbAgjuliesIzNvEnY/kMNjIMTPRn1n/O9wiOzxN9CoL2S8A9sabhn6ewepIK4HQf7u//+lXADw2PxkzJa4PcAuaAX+vMX+wIvLqz8jMphqR4dKEpZE2l+OtP1cm3JE8m/+ctrvan6d9FYaLBs4c+l2TmakWcjp8CNGOsgVOQRdTLxOWxAzPzHDpPxsHfk+a6Sj2WnGb9WYQyBSmnLRATSbKEzPBMOouIWgAj45vV6UmigfhMC34A8VSyAKyJJj2dTYXWHcykMwLNJHZ32YCKSFxpulEUlHs6k6aAdNH2B7i8wrL+TPx6UuAZJzTevMmlbCug53cLqmwNEp06h9/cfw8X2sl6cweBtPLY/+pe5FVrWf2t9d9W4Nh/tzeJV8KdbftFZvZRMwdqnkna2in1g9UYwcrEO0DcgcudVDDFvwuMeCOMpqb9vu1KEqUg2mi2F4Mh9wEAnFzDlkMY8Q1hrl5uiTHqLLXcKCC61JT6CFXMT64gvmq782yTGbmitknarxHd3gU5y6cFAgTZtSHiTGWv9rSBc+UL0THkXn26ihRt+hjp8BBZouhEq3Rem/WVRqxcrxGxo9LHHDAlvDwmUwtBZTvVsT/jmQtXi4qTED/0XgJ7J2WoDcazC3Z0v2DSUgXna11ldKCcLP4eNJhTEUD8ZDtgtXVN6n5x30zzG4uVSBZGaF549Yd2/o7i2vajClUuNDK/x22Q==
  template:
    metadata:
      name: ghcr-secret
      namespace: blackvoxel
    type: kubernetes.io/dockerconfigjson
