apiVersion: v1
kind: Secret
metadata:
  name: postgres-staging-secret
type: Opaque
stringData:
  # Used by the official postgres image.
  POSTGRES_DB: blackvoxel
  POSTGRES_USER: blackvoxel
  POSTGRES_PASSWORD: blackvoxel
