---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: blackvoxel
spec:
  encryptedData:
    credentials.json: AgCEQiAtf+pe9vFuEImXvlFd/DUVyP79nSzX6GMABzPKBE4/T3hZSuM3362p7nvmDU56HDpBAWskvkAGEi1JGtDHo6KL4RxQGgWRLL2kJO1RSw+B/kowoLw9HXPkQxI7yTiPD9KTEd3Zk0gXYQS26gtwjXJepDKEEhn1VqVxOrNFJje3VcBXBMhaqlVBiU4H+k3Yx7oPLRbCIjBSg8ds6QPRad93oz1jktHiawDdtbJijybDwT+hXxijOKWETQ6xGEeLFETnPXzCsxRBGQj3I4QDxVFzpWEdfjrygwRWS/+VNTbPSAHGmuv69yjaSpOnI26zpWcpmZSydx3hwvXcf5OJD0uvzGwxzn/Y1Qa7OQV9u6CpU05FEfd/+GNAbV0WcPb6zgVaSbBNGsImN2Yq7QyYarpHbFlXa6G4XTMEezDyaBCP/OLPXo9ioMnvNjCIcNAZ5dtywlhmdQ1NbJf2EcnhPT8KVahLiaKJWodQLT9WSTrlWdVEuGlsbcEGdbnXxPT3Iznu6pSP6OsVTTBMVjdqJcsI+4MVLts++COcjUnwIQQUJbHOf0OLgQubLG6TGjX0BAKk021UXYN7RPwGUdLgLqGyOvjemVLXMREheuPM9GXDAL7DrPH1ySrs0sxug0lAVsCj3wYsA75jrafdPq2daZwZ8elN+8Qip9YS5w7X6vxhwOFu9SpifOcEeasc9+cjDSa5xYs5TA+CwB2nyQuviO9Uoszx11uv7R+/suCQanU1hw8e1Nqaa2W5ErQ3pnJahtXCmIfwv+1QW91g37fidKCFmVsiW8OUzSRkoMrnFFtUST2ZVldNh3xzw3PHry/eiXpugficuyv8PUP3KozO43+jdB/Rir2jQYa6NkS541CUolxBOEM1Pv1Zqn1xyWS3G7SloY8oWRtgwwTNN+qTfVFw86dggAjSq+lnmiKL
  template:
    metadata:
      name: cloudflared-creds
      namespace: blackvoxel
